Q 1. You are given two strings s and t. String t is generated by randomly
shuffling string s and then adding one more letter at a random position.
Return the letter that was added to t.
- Examples
- find_the_difference(&quot;abcd&quot;, &quot;abcde&quot;) ➞ &quot;e&quot;
- find_the_difference(&quot;&quot;, &quot;y&quot;) ➞ &quot;y&quot;
- find_the_difference(&quot;ae&quot;, &quot;aea&quot;) ➞ &quot;a&quot;

ans :

In [26]:
def find_the_difference(s,t):
    t_sum = 0
    for i in t:
        t_sum +=ord(i)
    for i in s:
        t_sum -=ord(i)
    return chr(t_sum)

In [27]:
find_the_difference("abcd", "abcde")

'e'

In [28]:
find_the_difference("", "y")

'y'

In [29]:
find_the_difference("ae", "aea")

'a'

Q 2. Given a function that accepts unlimited arguments, check and count how
many data types are in those arguments. Finally return the total in a list.
List order is:
- [int, str, bool, list, tuple, dictionary]
- Examples
- count_datatypes(1, 45, &quot;Hi&quot;, False) ➞ [2, 1, 1, 0, 0, 0]
- count_datatypes([10, 20], (&quot;t&quot;, &quot;Ok&quot;), 2, 3, 1) ➞ [3, 0, 0, 1, 1, 0]
- count_datatypes(&quot;Hello&quot;, &quot;Bye&quot;, True, True, False, {&quot;1&quot;: &quot;One&quot;, &quot;2&quot;: &quot;Two&quot;}, [1,
3], {&quot;Brayan&quot;: 18}, 25, 23) ➞ [2, 2, 3, 1, 0, 2]
- count_datatypes(4, 21, (&quot;ES&quot;, &quot;EN&quot;), (&quot;a&quot;, &quot;b&quot;), False, [1, 2, 3], [4, 5, 6]) ➞ [2,
0, 1, 2, 2, 0]

ans :

In [30]:
def count_datatypes(*args):
    l = [0,0,0,0,0,0]
    for i in args:
        if type(i) == int:
            l[0]= l[0]+1
        elif type(i) == str:
              l[1] = l[1]+1
        elif type(i) == bool:
              l[2] = l[2]+1
        elif type(i) == list:
              l[3] = l[3]+1
        elif type(i) == tuple:
              l[4] = l[4]+1
        elif type(i) == dict:
              l[5] = l[5]+1

    return l

In [31]:
count_datatypes(1, 45, "Hi", False)

[2, 1, 1, 0, 0, 0]

In [32]:
count_datatypes([10, 20], ("t", "Ok"), 2, 3, 1)

[3, 0, 0, 1, 1, 0]

In [33]:
count_datatypes("Hello", "Bye", True, True, False, {"1": "One", "2": "Two"}, [1, 3], {"Brayan": 18}, 25, 23)

[2, 2, 3, 1, 0, 2]

In [34]:
count_datatypes(4, 21, ("ES", "EN"), ("a", "b"), False, [1, 2, 3], [4, 5, 6])

[2, 0, 1, 2, 2, 0]

Q 3. A Fibonacci string is a precedence of the Fibonacci series. It works with
any two characters of the English alphabet (as opposed to the numbers 0 and
1 in the Fibonacci series) as the initial items and concatenates them together
as it progresses in a similar fashion as the Fibonacci series.
- Examples
- fib_str(3, [&quot;j&quot;, &quot;h&quot;]) ➞ &quot;j, h, hj&quot;
- fib_str(5, [&quot;e&quot;, &quot;a&quot;]) ➞ &quot;e, a, ae, aea, aeaae&quot;
- fib_str(6, [&quot;n&quot;, &quot;k&quot;]) ➞ &quot;n, k, kn, knk, knkkn, knkknknk&quot;

ans :

In [35]:
def fib_str(num,list):
    a = list[0]
    b = list[1]
    l = []
    for n in range(0,num):
        if n < 0:
            print("Incorrect input")
        elif n == 0:
            l.append(a)
        elif n == 1:
            l.append(b)
        else:
            for i in range(1, n):
                c = b + a
                a = b
                b = c
                l.append(b) 
    return l[:num]

In [36]:
fib_str(3, ["j", "h"])

['j', 'h', 'hj']

In [37]:
fib_str(5, ["e", "a"])

['e', 'a', 'ae', 'aea', 'aeaae']

In [38]:
fib_str(6, ["n", "k"])

['n', 'k', 'kn', 'knk', 'knkkn', 'knkknknk']

Q 4. Given an integer between 0 and 26, make a variable (self.answer). That
variable would be assigned to a string in this format:
- &quot;nines:your answer, threes:your answer, ones:your answer&quot;
- You need to find out how many ones, threes, and nines it would at least take
for the number of each to add up to the given integer when multiplied by one,
three or nine (depends).
- Examples
- ones_threes_nines(10) ➞ &quot;nines:1, threes:0, ones:1&quot;
- ones_threes_nines(15) ➞ &quot;nines:1, threes:2, ones:0&quot;
- ones_threes_nines(22) ➞ &quot;nines:2, threes:1, ones:1&quot;

ans:

In [48]:
def ones_threes_nines(num):
    nines = num // 9
    threes = (num%9) // 3
    ones = num % 3
    print("Nines:", nines," Threes:", threes," Ones:", ones)

In [49]:
ones_threes_nines(10)

Nines: 1  Threes: 0  Ones: 1

In [50]:
ones_threes_nines(15)

Nines: 1  Threes: 2  Ones: 0

In [51]:
ones_threes_nines(22)

Nines: 2  Threes: 1  Ones: 1

Q 5. The Fibonacci sequence is a classic use case for recursive functions since
the value of the sequence at a given index is dependent on the sum of the
last two values. However, the recursion tree created by solving the Fibonacci
sequence recursively can grow quite fast. Therefore it can be important to
think about the implications of running a function recursively. Depending on
the size of n needed and the capabilities of the system in question you might
want to take a different approach.
- Write a non-recursive function that takes an integer n and returns the
Fibonacci sequence&#39;s value at index n.
- Examples
- fib(6) ➞ 8
- 0 + 1 = 1, 1 + 1 = 2, 1 + 2 = 3, 2 + 3 = 5, 3 + 5 = 8
- fib(1) ➞ 1
- fib(2) ➞ 1

ans :

In [44]:
def fib(num):
    a = 0
    b = 1
    if num ==0:
        return 0
    elif num == 1:
        return b
    else :
        for i in range(1,num):
            c = a+b
            a = b
            b = c
        return b

In [45]:
fib(6)

8

In [46]:
fib(1)

1

In [47]:
fib(2)

1